name = "ExamplePkg"
uuid = "ace499af-7767-4b69-905c-44038c8ba98b"
authors = ["ruochengzhai <rzhai@psu.edu>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
PlutoTeachingTools = "661c6b06-c737-4d37-b85c-46df65de6f69"
PlutoTest = "cb4044da-4d16-4ffa-a6a3-8cad7f73ebdc"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BenchmarkTools = "1.6.3"
Conda = "1.10.3"
Distances = "0.10.12"
FITSIO = "0.17.5"
InteractiveUtils = "1.11.0"
LazyArrays = "2.8.0"
LinearAlgebra = "1.11.0"
LsqFit = "0.15.1"
Markdown = "1.11.0"
OhMyThreads = "0.8.3"
PlutoTeachingTools = "0.4.6"
PlutoTest = "0.2.2"
PlutoUI = "0.7.73"
PyCall = "1.96.4"
Random = "1.11.0"
Statistics = "1.11.1"
StatsBase = "0.34.7"
Tables = "1.12.1"
Test = "1.11.0"
